### ISSUE TITLE
Mod not working in survival mode (minetest_game)

### ISSUE THREAD

**Issue by Alatarius** [mt-mods/technic#304] opened 2023-05-14 20:47 UTC
I made a lighting system with the low voltage items. I have a double 5x5 LV solar array which connects to a bank of 12 LV battery boxes. These in turn connect to a series of lights in my base. This Low voltage system is connected to nothing but the LV Lamps. The MV system I have works just fine in either mode. JUST the LV system stops working in survival mode

This system works only if I'm in creative mode. If I switch to survival mode the entire lighting system never works and all lights are off.

[edit] Also wanted to add that if I switch to survival mode the battery boxes discharge and won't recharge.

This is the what I have for power supply (see image)
![nopower2](https://github.com/mt-mods/technic/assets/101660302/84b5dd6d-bcc1-438b-a790-cadd185ce5fc)

**Comment by S-S-X** [comment] 2023-05-14 21:07
This probably has something weird to do with switching between creative and survival because I can confirm mod works well in survival mode on active servers.

Could you try crafting Multimeter and using it on your network and post screenshot both when it works (supposedly when in creative) and when it doesn't (apparently in survival)?
Tool needs to be charged so if you cannot charge it in survival then maybe try creative first and charge it there.

**Comment by S-S-X** [comment] 2023-05-14 21:12
Also are you using:
* Latest version from GitHub master branch?
* Or "Technic Plus Beta" from ContentDB? (same as latest from GitHub)
* Or "Technic Plus" from ContentDB? (not latest stuff but should work just fine)

**Comment by OgelGames** [comment] 2023-08-07 11:40
Closing this until more information is provided.

**Closed by OgelGames** 2023-08-07 11:40 UTC
Labels: Bug

**Comment by Alatarius** [comment] 2023-08-07 14:05
Yes I am using the latest version from here on GitHub, And no I'm not using any other mods.
